baseURL = "https://lifematrix.github.io/"
languageCode = "en-us"
title = "LifeMatrix"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  description = "Computation · AI · Physcial Science"

  [params.profileMode]
    enabled = true
    title = "LifeMatrix"
    #subtitle = "Compilers · Cryptography · Scientific Computing"
    subtitle = "Computation · AI · Physical Science"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
